title: Shivam Ahirao # your name (or website title) here
logo: "/images/passport_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Python |Tableau |Data Visualization |BI| Informatica 
  <br><br>
  <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
  <div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="en_US" data-type="vertical" data-theme="dark" data-vanity="shivam-ahirao-30796810b"><a class="LI-simple-link" href='https://in.linkedin.com/in/shivam-ahirao-30796810b?trk=profile-badge'>Shivam Ahirao</a></div>
  <a href="https://www.linkedin.com/in/shivam-ahirao-30796810b/">View My LinkedIn Profile</a> 
 

google_analytics: UA-100565780-1 # your Google Analytics tracking ID here

theme: jekyll-theme-minimal
