title:  Shivam Ahirao # your name (or website title) here
logo: "/images/passport_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Python |Tableau |Data Visualization |BI | Informatica 
  <br><br>
  <a href="https://www.linkedin.com/in/shivam-ahirao-30796810b/">View My LinkedIn Profile</a> 

google_analytics: UA-100565780-1 # your Google Analytics tracking ID here

theme: jekyll-theme-minimal
highlighter: rouge
