title: Shivam Ahirao # your name (or website title) here
logo: "/images/passport_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Python | BI | Informatica | Data Visualization | Tableau
  <br><br>
   Ever since i was a child I always had a passion of building things,
   from breaking toy cars and making a windmill out of it In “Science Exhibition” to participating
   in “Hackathon’s” while pursuing Engineering.
   I believe in lifelong learning ;)
  <br><br>
  <a href="https://www.linkedin.com/in/shivam-ahirao-30796810b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-100565780-1 # your Google Analytics tracking ID here
