title:  Shivam Ahirao # your name (or website title) here
logo: "/images/portfolio.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Big Data | Data Visualization | BI
  <br><br>
  <a href="https://www.linkedin.com/in/shivam-ahirao-30796810b/">Linkedin Profile</a><br>
  <a href="http://shivamahirao.blogspot.com/">Blog</a><br>
  <a href="https://github.com/beingshivam/beingshivam.github.io/blob/master/pdf/Shivam_Ahirao_resume.pdf">Download Resume</a>
  

google_analytics: UA-100565780-1 # your Google Analytics tracking ID here
plugins:
  - jekyll-seo-tag

theme: jekyll-theme-minimal
highlighter: rouge
