title: Shivam Ahirao # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   
  <div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="en_US" data-type="vertical" data-theme="dark" data-vanity="shivam-ahirao-30796810b"><a class="LI-simple-link" href='https://in.linkedin.com/in/shivam-ahirao-30796810b?trk=profile-badge'>Shivam Ahirao</a></div>
  
 

google_analytics: UA-100565780-1 # your Google Analytics tracking ID here
<script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
theme: jekyll-theme-minimal
